#!/bin/sh

path="/sys/class/backlight/intel_backlight"
BRIGHTNESS=$(less "$path/brightness")
MAX_BRIGHTNESS=$(less "$path/max_brightness") 

percent="scale=2 ; $BRIGHTNESS / $MAX_BRIGHTNESS"
percent=$(echo "$percent" | bc)
echo $(echo "$percent" | cut -d'.' -f 2)%
